### PR TITLE
chore: centered loader

### PR DESCRIPTION
**Pull request by eYinka**
Fix for making loading spinner centered.

Goodluck on the project :)

### CODE REVIEW

**Comment by SahilDhingraa** [comment]
thanks for the help. :)

**Review by SahilDhingraa — COMMENTED** [review]
best way to center the loader, thanks.

**Comment by eYinka** [comment]
Awesome @SahilDhingraa 

You can mark the response as the right answer on stackoverflow then so it can help others. Cheers mate :)

**Comment by SahilDhingraa** [comment]
yeah Done!

**Pull request merged**
